### ISSUE TITLE
Issue 3.8.5. Hosting documentation online on page /03-how-to-package-a-python.html

### ISSUE THREAD

**Issue by allabur** [py-pkgs/py-pkgs#130]
Read the docs changing and recommended new `.readthedocs.yml`:

```
# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# We recommend specifying your dependencies to enable reproducible builds:
# https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
  install:
  - requirements: docs/requirements.txt
```
