### ISSUE TITLE
Add instructions on how to handle branch protection

### ISSUE THREAD

**Issue by ttimbers** [py-pkgs/py-pkgs#144]
GitHub has much better features for dealing with branch protection and PSR now. Below I show how we can possibly do this at current. I say possible because this has yet to be formally documented by PSR, and is still just reported in an issue: <https://github.com/python-semantic-release/python-semantic-release/issues/311>. I have tested it and it works for me, see example here: <https://github.com/ttimbers/pycounts_tt_2024/blob/main/.github/workflows/ci-cd.yml>

1. Create a new GitHub PAT (see [these docs](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token)) with the [repo](https://docs.github.com/en/developers/apps/building-oauth-apps/scopes-for-oauth-apps#available-scopes) scope.

2. Under **"Secrets"**, click on **"Settings and variables"** > **"Actions"**, and then under **"Repository secrets"** click **"New repository secret"** to create a new repository secret named `RELEASE_TOKEN` and the new GitHub PAT with repo scope as its value.

3. Edit the to `cd` job steps shown below (from `ci-cd.yml`) use this token:

```
...
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.RELEASE_TOKEN }}
...
    - name: Python Semantic Release
      uses: relekang/python-semantic-release@master
      with:
        github_token: ${{ secrets.RELEASE_TOKEN }}
        pypi_token: ${{ secrets.PYPI_API_TOKEN }}
...
```
